# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

# Example 1:
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:
# Input: s = "", t = "y"
# Output: "y"


from collections import Counter
def find_difference(s, t):
    s_count = Counter(s)
    t_count = Counter(t)

    for key, value in t_count.items():
        
        if t_count[key] > s_count.get(key, 0):
            print(key)




s = "abcd"
t = "abcde"
find_difference(s,t)
    
